### PR TITLE
Add administrative metadata to repository

### PR DESCRIPTION
**Pull request by ablwr**
I propose adding a defined copyright statement, code of conduct, and maintainers. And I volunteer as maintainer, since I originally made this repository and have made the most contributions to it. But other people who wish to be maintainers on this project should certainly volunteer too. (Perhaps @retokromer, and @todrobbins I know you are quite dedicated to amiaopensource works as well). It is better to have at least two maintainers, I think.

### CODE REVIEW

**Comment by retokromer** [comment]
Quick answers:
- I’m in favour of a copyright statement and I suggest a CC BY licence.
- I’m personally skeptical about the utility on CoCs IRL, but I support e.g. «Jérôme»’s one.
- Even though I’ll continue to contribute, I prefer not to be formally a maintainer.

**Comment by ablwr** [comment]
open-workflows unofficially follows a lot of the same patterns as the "awesome list" collection, and these are their [guidelines](https://github.com/sindresorhus/awesome/blob/master/create-list.md). They recommend the same license and Code of Conduct that I applied here.

**Comment by retokromer** [comment]
Indeed Contributor Covenant is what I meant as Jérôme’s.

**Comment by dericed** [comment]
@retokromer, some skepticism about the overall impact of a CoC may be fair (especially when considering how some of our professional organizations have utilized their CoC), but despite anyone's skeptical about the overall utility, each individual maintainer or contributor should personally make the same pledge as detailed in the code of conduct.

**Comment by retokromer** [comment]
>each individual maintainer or contributor should personally make the same pledge as detailed in the code of conduct.

That’s exactly my point: despite a clear CoC, IRL not all contributors are considered the same way.

**Comment by todrobbins** [comment]
image

I volunteer as a maintainer as well.

**Comment by ablwr** [comment]
Great!! Thanks @todrobbins

**Pull request merged**
