### PR TITLE
add dv white paper

### PR DESCRIPTION
**Pull request by ablwr**

### CODE REVIEW

**Comment by privatezero** [comment]
being a draft technical specification, could that belong under `Publications`?

**Comment by ablwr** [comment]
Oh yes, sorry! I forgot about that entire category.

**Comment by ablwr** [comment]
Thanks for being a real librarian

**Review by retokromer — APPROVED** [review]

**Comment by todrobbins** [comment]
apologies for being absent in helping with this repo, @ablwr! I'll keep a closer eye in the future 👀

**Comment by ablwr** [comment]
@todrobbins you are very excellent and there is no reason for apology whatsoever!

**Pull request merged**
