### PR TITLE
Add links

### PR DESCRIPTION
**Pull request by privatezero**
Added PS&V Scripts (aka UW scripts), Audacity and BWF Metaedit. Meh?

### CODE REVIEW

**Comment by ablwr** [comment]
:thinking: 💭 👍 👍 👍

**Comment by ablwr** [comment]
Not alphabetical though!

**Comment by privatezero** [comment]
Hey man! Scripts were already out of order! 😜

**Comment by ablwr** [comment]
HEY man. They were no...uh... oh. 😅

**Comment by ablwr** [comment]
Hey MAN only ONE was out of order!

**Pull request merged**
