### PR TITLE
add patch bay

### PR DESCRIPTION
**Pull request by bturkus**
think i'm doing this correctly; if not, lemme know.

### CODE REVIEW

**Comment by ablwr** [comment]
@bturkus you did it!!!!!!!!!!!!! 😄 😄 😄 😄 😄 😄 😄 😄 😸 

I will let @retokromer review... 😈

**Comment by dericed** [comment]
I have thoroughly reviewed this one line patch. Including a review of the well-formedness of the markdown linking, testing that the url works properly, checking that the url uses https when available, verified spelling, and checked for correct capitalization of BagIt. I'm about halfway done verifying that the blog is all around awesome as stated, but not blocking.

**Comment by kieranjol** [comment]
This is :fire:

**Comment by dinahhandel** [comment]
woot @bturkus

**Review by retokromer — APPROVED** [review]
LGTM

**Comment by retokromer** [comment]
Thank you very much!

**Comment by todrobbins** [comment]
Saved: https://web.archive.org/web/20170629070038/https://patchbaynyu.wordpress.com/nyu-miap/

**Pull request merged**
